---
language: python

python:
  - 3.5
  - 3.6
  - 3.7

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install flake8 pylint

jobs:
  include:
    - stage: flake8
      script: flake8 packer_builder/*.py
    - stage: pylint
      script: pylint packer_builder/*.py
    - stage: Install Packer
      env:
        - PACKER_VERSION="1.4.3"
      script: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
        unzip packer_${PACKER_VERSION}_linux_amd64.zip
        sudo mv packer /usr/local/bin
        echo "Packer Version: $(packer --version)"
    - stage: Generate Packer Templates
      script: python -m packer_builder generate-templates --outputdir ~/projects/packer
