---
name: CI

# yamllint disable-line rule:truthy
on: [push]

# yamllint disable rule:line-length
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with pylint
        run: |
          pylint **/*.py
      - name: Lint with yamllint
        run: |
          yamllint .
      - name: Install Packer
        env:
          PACKER_URL: https://releases.hashicorp.com/packer
          PACKER_VERSION: 1.4.3
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget ${PACKER_URL}/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo mv packer /usr/local/bin
          echo "Packer Version: $(packer --version)"
      - name: Generate Packer Templates
        run: |
          python -m packer_builder generate-templates \
          --outputdir ~/projects/packer
